name: Go package
on: [push]
jobs:
  build:
    name: 'Go Build (1.21)'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build ./...
  static:
    name: 'Go Static (1.21)'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - run: 'go install honnef.co/go/tools/cmd/staticcheck@latest'
      - run: 'go vet ./...'
      - run: 'staticcheck ./...'
  test:
    name: 'Go Test (1.21)'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: Install dependencies
        run: go get .
      - name: Test
        run: go test -cover -vet all -coverprofile cover.out .
      - name: Coverage report
        run: go tool cover -html ./cover.out -o cover.html
      - name: Archive coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage.html
          path: ./cover.html
