name: Go package
on: [push]
jobs:
  build:
    name: 'Go Build (1.21)'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build ./...
  static:
    name: 'Go Static (1.21)'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - run: 'go install honnef.co/go/tools/cmd/staticcheck@latest'
      - run: 'go vet ./...'
      - run: 'staticcheck ./...'
  test:
    name: 'Go Test (1.21)'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: Install dependencies
        run: go get .
      - name: Test
        run: go test -cover -vet all -coverprofile cover.out .
      - name: Coverage Check
        run: |
          go tool cover -func ./cover.out
          val=$(go tool cover -func cover.out | fgrep total | awk '{print $3}')
          if [[ "100.0%" != $val ]] 
          then
            echo 'Test coverage is less than 100.0%'
            exit 1
          fi
